home/urls.py
from django.urls import path
from .views import home, pagina_no_encontrada
from django.conf.urls import handler404

urlpatterns = [
    path('',home, name='home')
]

handler404 = 'home.views.pagina_no_encontrada'

redsocial/urls.py
from django.urls import path
from .views import mi_red, buscar_amigo, crear_publicacion, perfil_mascota, perfil_usuario, ver_galeria_mascota, detalle_img_mascota#, publicar_mensaje_usuario#, publicar_mensaje_mascota



urlpatterns=[
    path('mi-red/',mi_red, name='mi_red'),
    path('buscar-amigo/',buscar_amigo, name='buscar_amigo'),
    
    path('publicar/',crear_publicacion, name='crear_publicacion'),
    path('ver-perfil-usuario/<int:usuario_id>/',perfil_usuario, name='perfil_usuario'),
    path('ver-perfil-mascota/<int:mascota_id>/',perfil_mascota, name='perfil_mascota'),
    path('galeria-mascota/<int:mascota_id>/',ver_galeria_mascota, name='galeria_mascota'),
    path('galeria-mascota/img/<int:imagen_id>/',detalle_img_mascota, name='detalle_img_mascota'),
    #path('perfil-mascota/mensajes/<int:mascota_id>/',publicar_mensaje_mascota, name='publicar_mensaje_mascota'),
    #path('perfil-usuario/<int:usuario_id>/comentar/',publicar_mensaje_usuario, name='publicar_mensaje_usuario'),
   
    
    
    
    
]

webVeterinaria/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('acceso.urls')),
    path('', include('contacto.urls')),
    path('', include('servicios.urls')),
    path('', include('perfil.urls')),
    path('', include('chatbot.urls')),
    path('', include('redsocial.urls')),
   
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acceso/models.py
from django.contrib.auth.models import AbstractUser,  Group, Permission
from django.db import models

class DuenoMascota(AbstractUser):
    id = models.AutoField(primary_key=True)
    telefono = models.CharField(max_length=9)
    direccion = models.TextField()
    fechaNac = models.DateField(null=True, blank=True)
    genero = models.CharField(max_length=20, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'),('Prefiero no decirlo','Prefiero no decirlo'),('Otro','Otro')])
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True, null=False)
    tiene_mascota= models.BooleanField(default=False)
    imagen_perfil = models.ImageField(upload_to='dueno_img/', blank=True, null=True)

    def __str__(self):
        return self.username
    
    
class TipoUsuario(models.Model):
    TIPOS_USUARIO = [
        ('dueno', 'Dueño de Mascota'),
        ('servicios', 'Ofrece Servicios'),
    ]
    id = models.AutoField(primary_key=True)
    tipo_usuario = models.CharField(max_length=20, choices=TIPOS_USUARIO)
    usuario = models.OneToOneField(DuenoMascota, on_delete=models.CASCADE)

    def __str__(self):
        return self.tipo_usuario
    
class Especie(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.nombre

class Raza(models.Model):
    especie = models.ForeignKey(Especie, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
    
class Mascota(models.Model):
    id = models.AutoField(primary_key=True)
    dueno = models.ForeignKey(DuenoMascota, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    especie = models.ForeignKey(Especie, on_delete=models.CASCADE)
    raza = models.ForeignKey(Raza, on_delete=models.CASCADE)
    fecha_nacimiento_mascota = models.DateField(null=True, blank=True)
    genero_mascota = models.CharField(max_length=20, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')])
    color = models.CharField(max_length=100, blank=True)
    historial_medico = models.TextField(blank=True)
    imagen = models.ImageField(upload_to='mascotas_img/', blank=True)
    identificacion = models.CharField(max_length=50, blank=True)
    vacunacion = models.TextField(blank=True)
    comportamiento = models.TextField(blank=True)
    alimentacion = models.TextField(blank=True)
    entrenamiento = models.TextField(blank=True)
    otros_cuidados = models.TextField(blank=True)
    
    def __str__(self):
        return self.nombre
    

redsocial/forms.py
from django import forms
from .models import Publicacion, GaleriaMascota, Comentario, Mensaje , ComentarioUsuario

class PublicacionForm(forms.ModelForm):
    # Define un campo de elección para el tipo de actividad
    tipo_actividad = forms.ChoiceField(
        choices=Publicacion.TIPOS_ACTIVIDAD,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    contenido = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Comparte algo...'}),
    )

    class Meta:
        model = Publicacion
        fields = ['tipo_actividad', 'contenido']
        labels = {
            'tipo_actividad': 'Tipo de Actividad',
            'contenido': 'Contenido',
        }




class BusquedaAmigoForm(forms.Form):
    OPTIONS = [
        ('usuario', 'Nombre de Usuario'),
        ('mascota', 'Nombre de Mascota'),
    ]

    query = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Ingresa nombre de usuario o mascota'}),
    )

    search_by = forms.ChoiceField(
        choices=OPTIONS,
        widget=forms.RadioSelect,
        required=True,
        initial='usuario',  # Puedes establecer el valor inicial aquí
    )
    
class GaleriaMascotaForm(forms.ModelForm):
    class Meta:
        model = GaleriaMascota
        fields = ['imagen', 'descripcion']
        widgets = {
        'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        'descripcion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Agrega una descripción'}),
    }
        



class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario  # Asocia el formulario con el modelo Comentario
        fields = ['contenido']  # Especifica los campos que se mostrarán en el formulario

        widgets = {
            'contenido': forms.Textarea(attrs={'class': 'form-control','placeholder':'Agrega un comentario aquí..'}),
        }
        labels = {
            'contenido': 'Comentario',
        }

'''class MensajeForm(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = ['contenido']

        widgets = {
            'contenido': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escribe tu mensaje aquí...'}),
        }'''


class MensajeForm(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = ['contenido', 'tipo_mensaje']

        widgets = {
            'contenido': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escribe tu mensaje aquí...'}),
            'tipo_mensaje': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipo_mensaje'].widget.choices = Mensaje.TIPO_MENSAJE


class ComentarioUsuarioForm(forms.ModelForm):
    class Meta:
        model = ComentarioUsuario
        fields = ['contenido', 'tipo_mensaje']

        widgets = {
            'contenido': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escribe tu mensaje aquí...'}),
            'tipo_mensaje': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipo_mensaje'].widget.choices = ComentarioUsuario.TIPO_MENSAJE

redsocial/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PublicacionForm, BusquedaAmigoForm, GaleriaMascotaForm, ComentarioForm, MensajeForm, ComentarioUsuarioForm
from acceso.models import DuenoMascota, Mascota
from django.contrib.auth.models import User
from django.contrib import messages
from .models import GaleriaMascota, Comentario, Mensaje, ComentarioUsuario
from acceso.models import TipoUsuario
from django.contrib.auth.decorators import login_required



@login_required
def mi_red(request):
    tipo_usuario = None
    user_id = None  

    if request.user.is_authenticated:
        try:
            tipo_usuario_obj = TipoUsuario.objects.get(usuario=request.user)
            tipo_usuario = tipo_usuario_obj.tipo_usuario
            user_id = request.user.id  
        except TipoUsuario.DoesNotExist:
            tipo_usuario = None

    formulario = PublicacionForm()
    return render(request, 'redsocial/mi_red.html', {'formulario': formulario, 'tipo_usuario': tipo_usuario, 'user_id': user_id})


@login_required
def crear_publicacion(request):
    formulario = PublicacionForm()
    
    if request.method == 'POST':
        formulario = PublicacionForm(request.POST)
        if formulario.is_valid():
            nueva_publicación = formulario.save(commit=False)
            nueva_publicación.autor = request.user
            nueva_publicación.save()
            messages.success(request, 'Tu publicación se creó con éxito.')
            return redirect('mi_red')
    
    return render(request, 'redsocial/mi_red.html', {'formulario': formulario})





@login_required
def buscar_amigo(request):
    form = BusquedaAmigoForm()
    resultados = None
    tipo_usuario = None

    if request.user.is_authenticated:
        try:
            tipo_usuario_obj = TipoUsuario.objects.get(usuario=request.user)
            tipo_usuario = tipo_usuario_obj.tipo_usuario
        except TipoUsuario.DoesNotExist:
            tipo_usuario = None

    if request.method == 'GET':
        form = BusquedaAmigoForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            search_by = form.cleaned_data.get('search_by')

            # Traer a ambos tipos de usuarios excepto al superusuario
            if search_by == 'usuario':
                resultados = DuenoMascota.objects.filter(
                    tipousuario__tipo_usuario='dueno',
                    username__icontains=query
                ).exclude(is_superuser=True)
            elif search_by == 'mascota':
                resultados = Mascota.objects.filter(
                    nombre__icontains=query
                )

    return render(request, 'redsocial/buscar_amigo.html', {'form': form, 'resultados': resultados, 'tipo_usuario': tipo_usuario})



@login_required
def perfil_usuario(request, usuario_id):
    usuario_seleccionado = get_object_or_404(DuenoMascota, id=usuario_id)
    usuario_seleccionado_info = {
        'username': usuario_seleccionado.username,
        'email': usuario_seleccionado.email,
        # Otros campos que quieras mostrar del usuario seleccionado
    }

    # Verificar si el usuario autenticado es el dueño del perfil actual
    es_dueño_del_perfil = request.user == usuario_seleccionado

    # Obtener todos los comentarios
    comentarios = ComentarioUsuario.objects.filter(receptor=usuario_seleccionado)

    if not es_dueño_del_perfil:
        # Si no es el dueño, filtrar los comentarios por tipo 'Publico'
        comentarios = comentarios.filter(tipo_mensaje='Publico')

    if request.method == 'POST':
        form = ComentarioUsuarioForm(request.POST, instance=ComentarioUsuario(emisor=request.user, receptor=usuario_seleccionado))
        if form.is_valid():
            form.save()
            return redirect('perfil_usuario', usuario_id=usuario_id)

    else:
        form = ComentarioUsuarioForm()

    return render(request, 'redsocial/perfil_usuario.html', {
        'perfil': usuario_seleccionado,
        'comentarios': comentarios,
        'perfil_info': usuario_seleccionado_info,
        'form': form,
        'es_dueño_del_perfil': es_dueño_del_perfil,
    })


@login_required
def perfil_mascota(request, mascota_id):
    mascota = get_object_or_404(Mascota, id=mascota_id)
    tipo_usuario = None 

    if request.user.is_authenticated:
        try:
            tipo_usuario_obj = TipoUsuario.objects.get(usuario=request.user)
            tipo_usuario = tipo_usuario_obj.tipo_usuario
        except TipoUsuario.DoesNotExist:
            tipo_usuario = None

    mensajes = Mensaje.objects.filter(receptor=mascota)

    # Permitir que el dueño de la mascota vea tanto mensajes públicos como privados
    if tipo_usuario == 'Dueño' and request.user == mascota.dueno:
        mensajes = Mensaje.objects.filter(receptor=mascota)

    if request.method == 'POST':
        form = MensajeForm(request.POST)
        if form.is_valid():
            nuevo_mensaje = form.save(commit=False)
            nuevo_mensaje.emisor = request.user
            nuevo_mensaje.receptor = mascota
            nuevo_mensaje.save()
    else:
        form = MensajeForm()

    return render(request, 'redsocial/perfil_mascota.html', {'perfil': mascota, 'tipo_usuario': tipo_usuario, 'form': form, 'mensajes': mensajes})





@login_required
def ver_galeria_mascota(request, mascota_id):
    mascota = get_object_or_404(Mascota, id=mascota_id)
    form = GaleriaMascotaForm()
    es_dueno = request.user == mascota.dueno
    tipo_usuario = None  
    if request.user.is_authenticated:
        try:
            tipo_usuario_obj = TipoUsuario.objects.get(usuario=request.user)
            tipo_usuario = tipo_usuario_obj.tipo_usuario
        except TipoUsuario.DoesNotExist:
            tipo_usuario = None

    if request.method == 'POST' and 'imagen' in request.POST and es_dueno:
        form = GaleriaMascotaForm(request.POST, request.FILES)
        if form.is_valid():
            nueva_imagen = form.save(commit=False)
            nueva_imagen.mascota = mascota
            nueva_imagen.autor = request.user
            nueva_imagen.save()
            return redirect('galeria_mascota', mascota_id=mascota_id)

    galeria = GaleriaMascota.objects.filter(mascota=mascota)
    
    return render(request, 'redsocial/galeria.html', {'mascota': mascota, 'galeria': galeria, 'form': form, 'es_dueno': es_dueno, 'tipo_usuario': tipo_usuario})



@login_required
def detalle_img_mascota(request, imagen_id):
    imagen = get_object_or_404(GaleriaMascota, id=imagen_id)
    form = ComentarioForm()
    comentarios = Comentario.objects.filter(imagen=imagen)
    tipo_usuario = None  
    if request.user.is_authenticated:
        try:
            tipo_usuario_obj = TipoUsuario.objects.get(usuario=request.user)
            tipo_usuario = tipo_usuario_obj.tipo_usuario
        except TipoUsuario.DoesNotExist:
            tipo_usuario = None

    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            nuevo_comentario = form.save(commit=False)
            nuevo_comentario.autor = request.user
            nuevo_comentario.imagen = imagen
            nuevo_comentario.save()
            return redirect('detalle_img_mascota', imagen_id=imagen_id)

    return render(request, 'redsocial/detalle_foto.html', {'imagen': imagen, 'comentarios': comentarios, 'form': form, 'tipo_usuario': tipo_usuario})

redsocial/templates/redsocial/buscar_amigo.html
{% extends 'home/base.html' %}

{% block content %}

<body >
    <br>
    <div class="container" style="width: 80%; margin: auto;">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4 text-center">
                <h1 id="encabezadoFuente" class="text-center" style="background-color: lightsteelblue;">Mi Red Social
                </h1>
            </div>
            <div class="col-4"></div>
        </div>

        <!-- Enlaces de navegación basados en si el usuario está viendo su propio perfil o no -->
        <a href="{% url 'mi_perfil' %}" class="btn btn-warning">Mi Perfil</a>

        <div style="width: 60%; margin: auto;">
            <form method="get" action="{% url 'buscar_amigo' %}" style="background-color: lightsteelblue; border-radius: 10px; padding: 10px;">
                {{ form.query }}
                {{ form.search_by }}
                <br>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Buscar Amigo</button>
                </div>
                <br>
            </form>
        </div>
        <br>
        <!-- Agregar la lista de resultados aquí como tarjetas -->
        <div class="container" style="width: 90%; margin: auto; background-color: lightsteelblue; border-radius: 10px; padding: 10px;">
            {% if resultados %}
            <h2 id="encabezadoFuente" style="padding-top: 20px;">Resultados de la búsqueda:</h2>
            <div class="row row-cols-1 row-cols-md-3">
                {% if form.search_by.value == 'usuario' %}
                {% for usuario in resultados %}
                <div class="col mb-4">
                    <div class="card h-100" style="width: 18rem;">
                        {% if usuario.imagen_perfil.url != 'null' %}
                        <img src="{{ usuario.imagen_perfil.url }}" alt="{{ usuario.username }}"
                            class="imagen-redonda card-img-top img-fluid" style="height: 200px; object-fit: cover;">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ usuario.username }}</h5>
                            <p class="card-text mb-0">Nombre: {{ usuario.first_name }} {{ usuario.last_name }}</p>
                            <div class="text-center">
                                <a href="{% url 'perfil_usuario' usuario.id %}" class="btn btn-warning mt-2">Ver
                                    Perfil</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                {# Mostrar datos de mascotas si se busca por nombre de mascota #}
                {% for mascota in resultados %}
                <div class="col mb-4">
                    <div class="card h-100" style="width: 18rem;">
                        <img src="{{ mascota.imagen.url }}" alt="{{ mascota.nombre }}"
                            class="imagen-redonda card-img-top img-fluid" style="height: 200px; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title">{{ mascota.nombre }}</h5>
                            <p class="card-text mb-0">Especie: {{ mascota.especie }}</p>
                            <p class="card-text mb-0">Raza: {{ mascota.raza }}</p>
                            <p class="card-text mb-0">Género: {{ mascota.get_genero_mascota_display }}</p>
                            <p class="card-text mb-0">Color: {{ mascota.color }}</p>
                            <div class="text-center">
                                <a href="{% url 'perfil_mascota' mascota.id %}" class="btn btn-primary mt-2">Ver
                                    Perfil</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            {% else %}
            <p>No se encontraron resultados.</p>
            {% endif %}
        </div>
    </div>
    <br>
</body>

{% endblock %}

redsocial/templates/redsocial/comentario.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

    <div style="width: 50%;margin:auto;">
        <h2 class="text-center">Añadir un Comentario</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Comentar</button>
        </form>

        <!-- Mostrar los comentarios existentes -->
        <h2 class="text-center">Comentarios</h2>
        {% for comentario in comentarios %}
            {{ comentario.autor }} dijo: {{ comentario.contenido }}
        {% endfor %}
    </div>

redsocial/templates/redsocial/detalle_foto.html
{% extends 'home/base.html' %}

{% block content %}
    <div id="detalle" >
        <div style="padding:10px;">
            
            <a href="{% url 'galeria_mascota' imagen.mascota.id %}" class="btn btn-secondary">Volver a la galería</a>
        </div>
        
        <h1 class="text-center">Detalle de la Imagen</h1>

        <div class="card" style="width: 50%; margin: auto; text-align: center;">
            <div class="card-image" style="display: inline-block;">
                <img src="{{ imagen.imagen.url }}" alt="{{ imagen.descripcion }}" style="max-width: 100%; max-height: 100%;">
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ imagen.descripcion }}</h5>
                <p class="card-text">Dueño: {{ imagen.autor.username }}</p>
                <!-- Agrega otros detalles de la imagen de la mascota aquí si es necesario -->
            </div>
        </div>

        <!-- Agrega los comentarios y otros detalles aquí si es necesario -->
        {% include 'redsocial/comentario.html' %}
        <br>
        
    </div>
{% endblock %}

redsocial/templates/redsocial/galeria.html
{% extends 'home/base.html' %}

{% block content %}

<div class="row">
    <div class="col-4"></div>
    <div class="col-4 text-center">
        <h1 id="encabezadoFuente" class="text-center" style="background-color: lightsteelblue;">Galería de {{mascota.nombre|title }}
        </h1>
    </div>
    <div class="col-4"></div>
</div>

<div style="padding:10px;">
    <a href="{% url 'perfil_mascota' mascota.id %}" class="btn btn-warning">Volver al Perfil</a>
</div>
<div class="row">
    {% for imagen in galeria %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <a href="{% url 'detalle_img_mascota' imagen.id %}" style="text-decoration: none; ">
                <img class="card-img-top img-zoom" src="{{ imagen.imagen.url }}" alt="{{ imagen.descripcion }}">
                <div class="card-body">
                    <p class="card-text">{{ imagen.descripcion }}</p>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Agregar un formulario para cargar una nueva imagen (solo si es_dueno es True) -->
{% if es_dueno %}
<div style="width: 40%;margin:auto;">
    <h2>Subir nueva imagen</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="imagen" class="btn btn-primary">Subir Imagen</button>
    </form>
</div>
{% endif %}
{% endblock %}

redsocial/templates/redsocial/mensaje.html
{% extends 'home/base.html' %}

{% block content %}
<div class="container">
    <a href="{% url 'perfil_mascota' mascota_id %}" class="btn btn-warning">Volver Perfil</a>
       
    <div class="row">
        <div class="col-md-4">
            <!-- Columna para el formulario de envío de mensajes -->
            <div style="margin-top: 20px;">
                <h2 class="text-center">Deja tu mensaje</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Enviar Mensaje</button>
                </form>
            </div>
        </div>
        <div class="col-md-8">
            <!-- Columna para mostrar los mensajes -->
            <h2 class="text-center">Mensajes Recibidos:</h2>
            <ul>
                {% for mensaje in mensajes %}
                    <li>{{ mensaje.contenido }} - {{ mensaje.emisor }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

redsocial/templates/redsocial/mi_red.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="text-center">
        <h1>Mi Red</h1>
    </div>
  <section style="width: 40%;margin:auto; ">
    
    <a href="{% url 'buscar_amigo' %}" class="btn btn-warning">Buscar Amigos</a>
    <a href="{% url 'mi_perfil'  %}" class="btn btn-warning">Mi Perfil</a>
    <a href="{% url 'mi_mascota' %}" class="btn btn-warning">Mi Mascota</a>
  </section>

  <section style="width: 60%; margin:auto;">
    <h2>Quieres Compartir algo</h2>
    <form method="post" action="{% url 'crear_publicacion' %}">
        {% csrf_token %}
        {{ formulario }}
        <button type="submit" class="btn btn-primary">Publicar</button>
    </form>

    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
  </section>
{% endblock %}

redsocial/templates/redsocial/perfil_mascota.html
{% extends 'home/base.html' %}

{% block content %}

<body>
    <div class="container mt-4">
        <br>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4 text-center">
                <h1 id="encabezadoFuente" style="text-transform: capitalize; background-color: lightsteelblue;"
                    class="text-center">{{ perfil.nombre }}</h1>
            </div>
            <div class="col-4"></div>
        </div>
        <div style="padding: 10px;">
            <button class="btn btn-primary" onclick="goBack()">Volver</button>
            {% if user.is_authenticated and user == perfil.dueno %}
            <a href="{% url 'agregar_mascota' %}" class="btn btn-success">Registrar Nueva Mascota</a>
            {% endif %}
            <a href="{% url 'mi_perfil' %}" class="btn btn-warning">Mi Perfil</a>
            <a href="{% url 'galeria_mascota' perfil.id %}" class="btn btn-warning">Galería</a>
            <a href="{% url 'buscar_amigo' %}" class="btn btn-warning">Buscar Amigo</a>
            {% if user.is_authenticated and user == perfil.dueno %}
            <a href="#" class="btn btn-warning">Ficha Clínica</a>
            {% endif %}
            
        </div>
        <br>
        <!-- Imagen de perfil y información en una fila -->
        <div class="row">
            <div class="col-md-4 mb-4">
                <div class="card" style="width: 18rem;">
                    {% if perfil.imagen %}
                    {% if perfil.imagen.url %}
                    <img id="imagen-mascota" src="{{ perfil.imagen.url }}" alt="MASCOTA NO CUENTA CON FOTO DE PERFIL"
                        class="imagen-redonda">
                    {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="col-md-8 mb-4">
                <div class="card"
                    style="width: 18rem; padding: 10px; background-color: lightsteelblue; border-radius: 5%;">
                    <div class="card-body">

                        <p id="marginText" class="card-text">Especie: {{ perfil.especie }}</p>
                        <p id="marginText" class="card-text">Raza: {{ perfil.raza }}</p>
                        <p id="marginText" class="card-text">Género: {{ perfil.genero_mascota }}</p>
                        <p id="marginText" class="card-text">Color: {{ perfil.color }}</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Formulario y Lista de mensajes -->
        <div class="row" style="padding: 10px; background-color: lightsteelblue; border-radius: 10px;">
            <div class="col-md-4">
                <h2 style="margin-top: 20px;" class="text-center" id="encabezadoFuente">Deja tu mensaje</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Enviar Mensaje</button>
                    </div>
                </form>
            </div>
            <div class="col-md-8">
                <h2 style="margin-top: 20px;" class="text-center" id="encabezadoFuente">Mensajes Recibidos:</h2>
                <div class="row">
                    <div class="col-3"></div>
                    <div class="col-7" style="border: 2px black; background-color: white; border-radius: 10px; padding: 10px;">
                        <ul>
                            {% for mensaje in mensajes %}
                            {% if mensaje.tipo_mensaje == 'Publico' or user == mensaje.emisor or user == mensaje.receptor.dueno%}
                            <li>{{ mensaje.contenido }} - {{ mensaje.emisor }}</li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-2"></div>
                </div>
            </div>
        </div>
        <br>
</body>

<script>

function goBack() {
            window.history.back();
        }
        
</script>
{% endblock %}